### ISSUE TITLE
Netflix/fast_jsonapi abandoned

### ISSUE THREAD

**Issue by xhs345** [stas/jsonapi.rb#10] opened 2019-11-14 23:25 UTC
It looks like the project is no longer maintained by Netflix and this library depends on it, which makes me a bit hesitant to start using it. See: https://github.com/Netflix/fast_jsonapi/issues/433

This is a new fork that seems to be the best alternative atm: https://github.com/fast-jsonapi/fast_jsonapi/issues/1

**Comment by stas** [comment] 2019-11-15 12:06
@xhs345 thank you, we're aware of the status of the upstream project, that's one of the main reasons I joined the folks behind the fork. We're [trying to start a communication channel](https://github.com/fast-jsonapi/fast_jsonapi/issues/1#issuecomment-549982120) with the original authors in order to find a solution.

I'll close this, since this is more of a `fast_jsonapi` issue, and the issue you provided is a much better place to track the updates. Please feel free to open a new issue if you're having problems getting the two gems work together.

Thanks again :bowing_man: !

**Closed by stas** 2019-11-15 12:06 UTC

**Comment by xhs345** [comment] 2019-11-15 23:54
Oh, great to hear that you joined them. I suppose the actual issue I should've reported would be something like "Gem not compatible with Ruby 2.6" because of the dependency

**Comment by stas** [comment] 2019-11-16 17:28
@xhs345 could you please give an example how I can reproduce this incompatibility issue. [Our testsuite passes all tests on Ruby 2.6](https://github.com/stas/jsonapi.rb/runs/295652392), that's why I advise you to open a separate issue where you can share exact steps to reproduce the problem.
